export const ROLES = ['Top', 'Jungle', 'Mid', 'Bot', 'Support']

export const DAMAGE_TYPES = ['AD', 'AP', 'Mixed', 'Tank']

export const PLAYSTYLES = [
  'Assassin',
  'Bruiser',
  'Engage',
  'Poke',
  'Sustain',
  'Split-push',
  'Hypercarry',
  'Utility',
]

export const DIFFICULTIES = ['Easy', 'Medium', 'Hard']

// A curated list of champions with their Data Dragon keys
export const CHAMPIONS = [
  { name: 'Ahri', key: 'Ahri' },
  { name: 'Akali', key: 'Akali' },
  { name: 'Alistar', key: 'Alistar' },
  { name: 'Amumu', key: 'Amumu' },
  { name: 'Annie', key: 'Annie' },
  { name: 'Ashe', key: 'Ashe' },
  { name: 'Blitzcrank', key: 'Blitzcrank' },
  { name: 'Brand', key: 'Brand' },
  { name: 'Caitlyn', key: 'Caitlyn' },
  { name: 'Camille', key: 'Camille' },
  { name: 'Darius', key: 'Darius' },
  { name: 'Diana', key: 'Diana' },
  { name: 'Draven', key: 'Draven' },
  { name: "Ekko", key: "Ekko" },
  { name: 'Ezreal', key: 'Ezreal' },
  { name: 'Fiora', key: 'Fiora' },
  { name: 'Fizz', key: 'Fizz' },
  { name: 'Garen', key: 'Garen' },
  { name: 'Graves', key: 'Graves' },
  { name: 'Hecarim', key: 'Hecarim' },
  { name: 'Irelia', key: 'Irelia' },
  { name: 'Janna', key: 'Janna' },
  { name: 'Jarvan IV', key: 'JarvanIV' },
  { name: 'Jax', key: 'Jax' },
  { name: 'Jinx', key: 'Jinx' },
  { name: 'Kai\'Sa', key: 'Kaisa' },
  { name: 'Kassadin', key: 'Kassadin' },
  { name: 'Katarina', key: 'Katarina' },
  { name: "Kayn", key: "Kayn" },
  { name: 'Kennen', key: 'Kennen' },
  { name: 'Kha\'Zix', key: 'Khazix' },
  { name: 'Kindred', key: 'Kindred' },
  { name: "Kog'Maw", key: "KogMaw" },
  { name: 'LeBlanc', key: 'Leblanc' },
  { name: 'Lee Sin', key: 'LeeSin' },
  { name: 'Leona', key: 'Leona' },
  { name: 'Lissandra', key: 'Lissandra' },
  { name: 'Lucian', key: 'Lucian' },
  { name: 'Lulu', key: 'Lulu' },
  { name: 'Lux', key: 'Lux' },
  { name: 'Malphite', key: 'Malphite' },
  { name: 'Master Yi', key: 'MasterYi' },
  { name: 'Miss Fortune', key: 'MissFortune' },
  { name: 'Mordekaiser', key: 'Mordekaiser' },
  { name: 'Morgana', key: 'Morgana' },
  { name: 'Nami', key: 'Nami' },
  { name: 'Nasus', key: 'Nasus' },
  { name: 'Nautilus', key: 'Nautilus' },
  { name: 'Nidalee', key: 'Nidalee' },
  { name: 'Nocturne', key: 'Nocturne' },
  { name: "Nunu & Willump", key: "Nunu" },
  { name: 'Olaf', key: 'Olaf' },
  { name: 'Orianna', key: 'Orianna' },
  { name: 'Pantheon', key: 'Pantheon' },
  { name: 'Pyke', key: 'Pyke' },
  { name: 'Riven', key: 'Riven' },
  { name: 'Rumble', key: 'Rumble' },
  { name: 'Ryze', key: 'Ryze' },
  { name: 'Samira', key: 'Samira' },
  { name: 'Sejuani', key: 'Sejuani' },
  { name: 'Senna', key: 'Senna' },
  { name: 'Seraphine', key: 'Seraphine' },
  { name: 'Sett', key: 'Sett' },
  { name: 'Shaco', key: 'Shaco' },
  { name: 'Shen', key: 'Shen' },
  { name: 'Singed', key: 'Singed' },
  { name: 'Sion', key: 'Sion' },
  { name: 'Sivir', key: 'Sivir' },
  { name: 'Soraka', key: 'Soraka' },
  { name: 'Sylas', key: 'Sylas' },
  { name: 'Syndra', key: 'Syndra' },
  { name: "Tahm Kench", key: "TahmKench" },
  { name: "Taliyah", key: "Taliyah" },
  { name: 'Talon', key: 'Talon' },
  { name: 'Thresh', key: 'Thresh' },
  { name: 'Tristana', key: 'Tristana' },
  { name: 'Tryndamere', key: 'Tryndamere' },
  { name: 'Twisted Fate', key: 'TwistedFate' },
  { name: 'Twitch', key: 'Twitch' },
  { name: 'Udyr', key: 'Udyr' },
  { name: 'Vayne', key: 'Vayne' },
  { name: 'Veigar', key: 'Veigar' },
  { name: "Vel'Koz", key: "Velkoz" },
  { name: "Vi", key: "Vi" },
  { name: 'Viktor', key: 'Viktor' },
  { name: 'Vladimir', key: 'Vladimir' },
  { name: 'Warwick', key: 'Warwick' },
  { name: 'Wukong', key: 'MonkeyKing' },
  { name: "Xayah", key: "Xayah" },
  { name: 'Xerath', key: 'Xerath' },
  { name: "Xin Zhao", key: "XinZhao" },
  { name: 'Yasuo', key: 'Yasuo' },
  { name: 'Yone', key: 'Yone' },
  { name: 'Yorick', key: 'Yorick' },
  { name: "Yuumi", key: "Yuumi" },
  { name: 'Zed', key: 'Zed' },
  { name: "Zilean", key: "Zilean" },
  { name: 'Ziggs', key: 'Ziggs' },
  { name: "Zoe", key: "Zoe" },
  { name: "Zyra", key: "Zyra" },
].sort((a, b) => a.name.localeCompare(b.name))

const DDRAGON_VERSION = '14.6.1'
const BASE = `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}`

export const getSplashUrl = (key) =>
  `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${key}_0.jpg`

export const getIconUrl = (key) =>
  `${BASE}/img/champion/${key}.png`

export const ROLE_COLORS = {
  Top: '#c8a96e',
  Jungle: '#4caf82',
  Mid: '#6eaaff',
  Bot: '#e05c5c',
  Support: '#b06ef0',
}

export const DAMAGE_COLORS = {
  AD: '#e05c5c',
  AP: '#6eaaff',
  Mixed: '#c8a96e',
  Tank: '#4caf82',
}
